### ISSUE TITLE
[Bug]: Missing user when creating revisions during seeding

### ISSUE THREAD

**Issue by ivan-orlov-13** [mansoorkhan96/filament-versionable#19] opened 2024-06-21 11:49 UTC
### What happened?

When I create new records of a versioned model during database seeding, the user_id in the table is null. And after that, in the blade template I get the error that there is no user at the very first revision. During seeding I have to authorize the user, which is not very clear.

### How to reproduce the bug

Create a seed for an empty model's table. 
Apply this seed. 
Open the resource page with versions.

### Package Version

0.0.8

### PHP Version

8.3.7

### Laravel Version

11.10.0

### Which operating systems does with happen with?

Linux

**Comment by mansoorkhan96** [comment] 2024-06-21 14:36
Hey @ivan-orlov-13 

Possible to share any code snippet to allow me to understand what are you trying to achieve.

**Comment by abbasmashaddy72** [comment] 2024-09-17 14:45
Hi,

When seeding data using a factory, it's common to encounter an issue where the user_id field is set to `null` since no user is logged in during the seeding process. While it's possible to handle this by creating a custom model that extends `Overtrue\LaravelVersionable\Version` and binding it in your `AppServiceProvider` to set a default user_id, this approach is not ideal.

A more straightforward and reliable solution would be to manually assign a valid `user_id` either directly in your database or as part of the seeding process. This will keep your data consistent and avoid potential issues related to setting global default values.

Let me know if you need any help with this.

@ivan-orlov-13 @mansoorkhan96 you can close this, as it's not a bug but something that should be handled manually.

**Comment by mansoorkhan96** [comment] 2024-09-21 04:54
This is a user land problem not a package level. However, user_id is nullable so i dont think you should have any problems.

**Closed** 2024-09-21 05:34 UTC
Labels: bug
